config:
  phases:
    - duration: 10
      arrivalRate: 10
      name: Warm up
  environments:
    production:
      target: "https://strapi-elgboffel.vercel.app/api/serverless"
      phases:
        - duration: 2
          arrivalRate: 10
          name: Warm up
        - duration: 5
          arrivalRate: 1000
          name: Ramp up load
    local:
      target: "http://127.0.0.1:3000/api/serverless"
      phases:
        - duration: 10
          arrivalRate: 100
  variables:
    fastifyApiWriteToken:
      - "{{ $processEnvironment.FASTIFY_API_WRITE_TOKEN }}"
    fastifyApiReadToken:
      - "{{ $processEnvironment.NEXT_PUBLIC_FASTIFY_API_READ_ONLY_TOKEN }}"
